/**
 * AUTO-GENERATED by scripts/generate-ipc-channels.ts
 * DO NOT EDIT MANUALLY — changes will be overwritten on next build.
 *
 * Source of truth: src/shared/ipc.ts → IPC_CHANNELS
 * Generated: 32 channels
 */

// ---------------------------------------------------------------------------
// Individual channel constants (typed as string literals)
// ---------------------------------------------------------------------------

export const CHANNEL_CREATE_PLAN = "plan:create" as const;
export const CHANNEL_GET_PLAN = "plan:get" as const;
export const CHANNEL_LIST_PLANS = "plan:list" as const;
export const CHANNEL_LIST_PROJECT_MEMORY = "project-memory:list" as const;
export const CHANNEL_REFRESH_PROJECT_STACK_PROFILE = "project-memory:refresh" as const;
export const CHANNEL_DELETE_PLAN = "plan:delete" as const;
export const CHANNEL_ARCHIVE_PLAN = "plan:archive" as const;
export const CHANNEL_UNARCHIVE_PLAN = "plan:unarchive" as const;
export const CHANNEL_RUN_TASK = "task:run" as const;
export const CHANNEL_RUN_ALL = "task:runAll" as const;
export const CHANNEL_CANCEL_RUN = "run:cancel" as const;
export const CHANNEL_RETRY_TASK = "task:retry" as const;
export const CHANNEL_SKIP_TASK = "task:skip" as const;
export const CHANNEL_SET_TASK_PENDING = "task:setPending" as const;
export const CHANNEL_APPROVE_TASK_PROPOSAL = "proposal:approve" as const;
export const CHANNEL_DISMISS_TASK_PROPOSAL = "proposal:dismiss" as const;
export const CHANNEL_ABORT_QUEUE = "queue:abort" as const;
export const CHANNEL_START_DISCOVERY = "discovery:start" as const;
export const CHANNEL_CONTINUE_DISCOVERY = "discovery:continue" as const;
export const CHANNEL_DISCOVERY_EVENT = "discovery:event" as const;
export const CHANNEL_WIZARD_GUIDANCE = "wizard:guidance" as const;
export const CHANNEL_INFER_STACK = "wizard:inferStack" as const;
export const CHANNEL_RUN_EVENT = "run:event" as const;
export const CHANNEL_GET_MODEL_CONFIG = "config:getModels" as const;
export const CHANNEL_UPDATE_MODEL_CONFIG = "config:updateModel" as const;
export const CHANNEL_GET_APP_SETTINGS = "config:getAppSettings" as const;
export const CHANNEL_UPDATE_APP_SETTINGS = "config:updateAppSettings" as const;
export const CHANNEL_DISCOVERY_SESSIONS = "discovery:sessions" as const;
export const CHANNEL_DISCOVERY_RESUME = "discovery:resume" as const;
export const CHANNEL_DISCOVERY_ABANDON = "discovery:abandon" as const;
export const CHANNEL_DISCOVERY_CANCEL = "discovery:cancel" as const;
export const CHANNEL_GET_RUN_EVENTS = "run:getEvents" as const;

// ---------------------------------------------------------------------------
// IPC_CHANNELS object (mirrors src/shared/ipc.ts, zod-free for preload)
// ---------------------------------------------------------------------------

export const IPC_CHANNELS = {
  createPlan: "plan:create",
  getPlan: "plan:get",
  listPlans: "plan:list",
  listProjectMemory: "project-memory:list",
  refreshProjectStackProfile: "project-memory:refresh",
  deletePlan: "plan:delete",
  archivePlan: "plan:archive",
  unarchivePlan: "plan:unarchive",
  runTask: "task:run",
  runAll: "task:runAll",
  cancelRun: "run:cancel",
  retryTask: "task:retry",
  skipTask: "task:skip",
  setTaskPending: "task:setPending",
  approveTaskProposal: "proposal:approve",
  dismissTaskProposal: "proposal:dismiss",
  abortQueue: "queue:abort",
  startDiscovery: "discovery:start",
  continueDiscovery: "discovery:continue",
  discoveryEvent: "discovery:event",
  wizardGuidance: "wizard:guidance",
  inferStack: "wizard:inferStack",
  runEvent: "run:event",
  getModelConfig: "config:getModels",
  updateModelConfig: "config:updateModel",
  getAppSettings: "config:getAppSettings",
  updateAppSettings: "config:updateAppSettings",
  discoverySessions: "discovery:sessions",
  discoveryResume: "discovery:resume",
  discoveryAbandon: "discovery:abandon",
  discoveryCancel: "discovery:cancel",
  getRunEvents: "run:getEvents"
} as const;

/** Type of a single IPC channel string value. */
export type IpcChannel = typeof IPC_CHANNELS[keyof typeof IPC_CHANNELS];

// ---------------------------------------------------------------------------
// ALL_CHANNELS Set (useful for preload contextBridge whitelist validation)
// ---------------------------------------------------------------------------

export const ALL_CHANNELS: ReadonlySet<IpcChannel> = new Set([
  CHANNEL_CREATE_PLAN,
  CHANNEL_GET_PLAN,
  CHANNEL_LIST_PLANS,
  CHANNEL_LIST_PROJECT_MEMORY,
  CHANNEL_REFRESH_PROJECT_STACK_PROFILE,
  CHANNEL_DELETE_PLAN,
  CHANNEL_ARCHIVE_PLAN,
  CHANNEL_UNARCHIVE_PLAN,
  CHANNEL_RUN_TASK,
  CHANNEL_RUN_ALL,
  CHANNEL_CANCEL_RUN,
  CHANNEL_RETRY_TASK,
  CHANNEL_SKIP_TASK,
  CHANNEL_SET_TASK_PENDING,
  CHANNEL_APPROVE_TASK_PROPOSAL,
  CHANNEL_DISMISS_TASK_PROPOSAL,
  CHANNEL_ABORT_QUEUE,
  CHANNEL_START_DISCOVERY,
  CHANNEL_CONTINUE_DISCOVERY,
  CHANNEL_DISCOVERY_EVENT,
  CHANNEL_WIZARD_GUIDANCE,
  CHANNEL_INFER_STACK,
  CHANNEL_RUN_EVENT,
  CHANNEL_GET_MODEL_CONFIG,
  CHANNEL_UPDATE_MODEL_CONFIG,
  CHANNEL_GET_APP_SETTINGS,
  CHANNEL_UPDATE_APP_SETTINGS,
  CHANNEL_DISCOVERY_SESSIONS,
  CHANNEL_DISCOVERY_RESUME,
  CHANNEL_DISCOVERY_ABANDON,
  CHANNEL_DISCOVERY_CANCEL,
  CHANNEL_GET_RUN_EVENTS
] as const);
