import { describe, it, expect } from "vitest";
import { readFileSync, writeFileSync, mkdtempSync, rmSync } from "node:fs";
import { resolve, join } from "node:path";
import { tmpdir } from "node:os";
import { execSync } from "node:child_process";
import { extractChannels, generateCode } from "./ipc-channel-core";

const ROOT = resolve(import.meta.dirname, "..");
const GENERATOR = resolve(ROOT, "scripts/generate-ipc-channels.ts");
const SOURCE_PATH = resolve(ROOT, "src/shared/ipc.ts");
const OUTPUT_PATH = resolve(ROOT, "src/preload/channel-names.ts");

/**
 * Helper: run the generator via tsx in a subprocess.
 * Returns { stdout, stderr, exitCode }.
 */
function runGenerator(args: string[] = []): {
  stdout: string;
  stderr: string;
  exitCode: number;
} {
  try {
    const result = execSync(
      `npx tsx "${GENERATOR}" ${args.join(" ")}`,
      {
        cwd: ROOT,
        encoding: "utf-8",
        stdio: ["pipe", "pipe", "pipe"]
      }
    );
    return { stdout: result, stderr: "", exitCode: 0 };
  } catch (error: unknown) {
    const err = error as { stdout?: string; stderr?: string; status?: number };
    return {
      stdout: err.stdout ?? "",
      stderr: err.stderr ?? "",
      exitCode: err.status ?? 1
    };
  }
}

describe("generate-ipc-channels", () => {
  describe("core extraction and generation", () => {
    it("extracts all channels from shared/ipc.ts using canonical parser", () => {
      const source = readFileSync(SOURCE_PATH, "utf-8");
      const entries = extractChannels(source);

      // Verify non-empty extraction
      expect(entries.length).toBeGreaterThan(0);

      // Spot-check known channels
      const channelMap = new Map(entries.map((e) => [e.key, e.value]));
      expect(channelMap.get("createPlan")).toBe("plan:create");
      expect(channelMap.get("getRunEvents")).toBe("run:getEvents");
      expect(channelMap.get("discoveryEvent")).toBe("discovery:event");
    });

    it("generates code containing all extracted channels", () => {
      const source = readFileSync(SOURCE_PATH, "utf-8");
      const entries = extractChannels(source);
      const generated = generateCode(entries);

      // Every extracted channel value should appear in the output
      for (const { key, value } of entries) {
        expect(generated).toContain(`"${value}"`);
        expect(generated).toContain(`${key}: "${value}"`);
      }
    });

    it("generated output matches committed channel-names.ts", () => {
      const source = readFileSync(SOURCE_PATH, "utf-8");
      const entries = extractChannels(source);
      const generated = generateCode(entries);
      const committed = readFileSync(OUTPUT_PATH, "utf-8");

      expect(committed).toBe(generated);
    });

    it("throws on source without IPC_CHANNELS", () => {
      expect(() => extractChannels("const foo = 42;")).toThrow("Could not find");
    });

    it("throws on empty IPC_CHANNELS object", () => {
      const emptySource = "export const IPC_CHANNELS = {} as const;";
      expect(() => extractChannels(emptySource)).toThrow("zero channel entries");
    });
  });

  describe("generated output structure", () => {
    it("has auto-generated header", () => {
      const output = readFileSync(OUTPUT_PATH, "utf-8");

      expect(output).toContain("AUTO-GENERATED by scripts/generate-ipc-channels.ts");
      expect(output).toContain("DO NOT EDIT MANUALLY");
    });

    it("generates UPPER_SNAKE_CASE individual constants", () => {
      const output = readFileSync(OUTPUT_PATH, "utf-8");

      expect(output).toContain('export const CHANNEL_CREATE_PLAN = "plan:create" as const;');
      expect(output).toContain('export const CHANNEL_GET_RUN_EVENTS = "run:getEvents" as const;');
      expect(output).toContain(
        'export const CHANNEL_DISCOVERY_EVENT = "discovery:event" as const;'
      );
    });

    it("generates IPC_CHANNELS mirror object", () => {
      const output = readFileSync(OUTPUT_PATH, "utf-8");

      expect(output).toContain("export const IPC_CHANNELS = {");
      expect(output).toContain('createPlan: "plan:create"');
      expect(output).toContain("} as const;");
    });

    it("generates ALL_CHANNELS Set", () => {
      const output = readFileSync(OUTPUT_PATH, "utf-8");

      expect(output).toContain("export const ALL_CHANNELS: ReadonlySet<IpcChannel>");
      expect(output).toContain("CHANNEL_CREATE_PLAN");
      expect(output).toContain("CHANNEL_GET_RUN_EVENTS");
    });

    it("generates IpcChannel type", () => {
      const output = readFileSync(OUTPUT_PATH, "utf-8");

      expect(output).toContain(
        "export type IpcChannel = typeof IPC_CHANNELS[keyof typeof IPC_CHANNELS];"
      );
    });
  });

  describe("CLI --check mode", () => {
    it("passes when generated file is up to date", () => {
      const result = runGenerator(["--check"]);
      expect(result.exitCode).toBe(0);
      expect(result.stdout).toContain("IPC channels are up to date");
    });

    it("fails when generated file is stale", () => {
      let tmpDir: string | undefined;
      try {
        tmpDir = mkdtempSync(join(tmpdir(), "ipc-check-test-"));
        const staleFile = join(tmpDir, "channel-names.ts");
        writeFileSync(staleFile, "// stale content\n", "utf-8");

        const result = runGenerator(["--check", "--output", staleFile]);
        expect(result.exitCode).toBe(1);
        expect(result.stderr).toContain("out of date");
      } finally {
        if (tmpDir) {
          rmSync(tmpDir, { recursive: true, force: true });
        }
      }
    });

    it("fails when generated file does not exist", () => {
      let tmpDir: string | undefined;
      try {
        tmpDir = mkdtempSync(join(tmpdir(), "ipc-check-test-"));
        const missingFile = join(tmpDir, "nonexistent.ts");

        const result = runGenerator(["--check", "--output", missingFile]);
        expect(result.exitCode).toBe(1);
        expect(result.stderr).toContain("does not exist");
      } finally {
        if (tmpDir) {
          rmSync(tmpDir, { recursive: true, force: true });
        }
      }
    });
  });

  describe("CLI generation to custom output", () => {
    it("writes to a custom output path", () => {
      let tmpDir: string | undefined;
      try {
        tmpDir = mkdtempSync(join(tmpdir(), "ipc-gen-test-"));
        const customOutput = join(tmpDir, "custom-channels.ts");

        const result = runGenerator(["--output", customOutput]);
        expect(result.exitCode).toBe(0);

        const content = readFileSync(customOutput, "utf-8");
        expect(content).toContain("AUTO-GENERATED");
        expect(content).toContain("IPC_CHANNELS");
      } finally {
        if (tmpDir) {
          rmSync(tmpDir, { recursive: true, force: true });
        }
      }
    });
  });
});
