/**
 * Shared extraction and code-generation logic for IPC channel constants.
 *
 * Consumed by:
 *   - scripts/generate-ipc-channels.ts  (CLI generator)
 *   - scripts/vite-plugin-ipc-channels.ts  (Vite build hook)
 *   - scripts/generate-ipc-channels.test.ts  (unit tests)
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface ChannelEntry {
  /** Key name from IPC_CHANNELS object, e.g. "createPlan" */
  key: string;
  /** Channel string value, e.g. "plan:create" */
  value: string;
}

// ---------------------------------------------------------------------------
// Extraction
// ---------------------------------------------------------------------------

/**
 * Parse the IPC_CHANNELS object from TypeScript source using regex.
 *
 * The object is a flat string-literal map:
 *   export const IPC_CHANNELS = { key: "value", ... } as const;
 *
 * We extract the block between the opening `{` and closing `}` then
 * pull each `key: "value"` pair.
 */
export function extractChannels(source: string): ChannelEntry[] {
  const objectMatch = source.match(
    /export\s+const\s+IPC_CHANNELS\s*=\s*\{([\s\S]*?)\}\s*as\s+const/
  );
  if (!objectMatch) {
    throw new Error(
      "Could not find 'export const IPC_CHANNELS = { ... } as const' in source."
    );
  }

  const objectBody = objectMatch[1];

  // Match each key: "value" pair (supports both single and double quotes)
  const entryPattern = /(\w+)\s*:\s*["']([^"']+)["']/g;
  const entries: ChannelEntry[] = [];
  let match: RegExpExecArray | null;

  while ((match = entryPattern.exec(objectBody)) !== null) {
    entries.push({ key: match[1], value: match[2] });
  }

  if (entries.length === 0) {
    throw new Error(
      "Extracted zero channel entries from IPC_CHANNELS. The object may have changed format."
    );
  }

  return entries;
}

// ---------------------------------------------------------------------------
// Code Generation Helpers
// ---------------------------------------------------------------------------

/**
 * Convert a camelCase channel key to UPPER_SNAKE_CASE for the constant name.
 * e.g. "createPlan" -> "CREATE_PLAN", "getRunEvents" -> "GET_RUN_EVENTS"
 */
export function toUpperSnake(camelCase: string): string {
  return camelCase
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .toUpperCase();
}

/**
 * Generate the full TypeScript source for channel-names.ts.
 */
export function generateCode(entries: ChannelEntry[]): string {
  const lines: string[] = [];

  // Header
  lines.push(
    "/**",
    " * AUTO-GENERATED by scripts/generate-ipc-channels.ts",
    " * DO NOT EDIT MANUALLY — changes will be overwritten on next build.",
    " *",
    " * Source of truth: src/shared/ipc.ts → IPC_CHANNELS",
    ` * Generated: ${entries.length} channels`,
    " */",
    "",
    "// ---------------------------------------------------------------------------",
    "// Individual channel constants (typed as string literals)",
    "// ---------------------------------------------------------------------------",
    ""
  );

  // Individual exports
  for (const { key, value } of entries) {
    const constName = `CHANNEL_${toUpperSnake(key)}`;
    lines.push(`export const ${constName} = "${value}" as const;`);
  }

  // IPC_CHANNELS mirror object
  lines.push(
    "",
    "// ---------------------------------------------------------------------------",
    "// IPC_CHANNELS object (mirrors src/shared/ipc.ts, zod-free for preload)",
    "// ---------------------------------------------------------------------------",
    "",
    "export const IPC_CHANNELS = {"
  );
  for (let i = 0; i < entries.length; i++) {
    const { key, value } = entries[i];
    const comma = i < entries.length - 1 ? "," : "";
    lines.push(`  ${key}: "${value}"${comma}`);
  }
  lines.push("} as const;");

  // Channel type
  lines.push(
    "",
    "/** Type of a single IPC channel string value. */",
    "export type IpcChannel = typeof IPC_CHANNELS[keyof typeof IPC_CHANNELS];"
  );

  // ALL_CHANNELS Set
  lines.push(
    "",
    "// ---------------------------------------------------------------------------",
    "// ALL_CHANNELS Set (useful for preload contextBridge whitelist validation)",
    "// ---------------------------------------------------------------------------",
    "",
    "export const ALL_CHANNELS: ReadonlySet<IpcChannel> = new Set(["
  );
  for (let i = 0; i < entries.length; i++) {
    const constName = `CHANNEL_${toUpperSnake(entries[i].key)}`;
    const comma = i < entries.length - 1 ? "," : "";
    lines.push(`  ${constName}${comma}`);
  }
  lines.push("] as const);", "");

  return lines.join("\n");
}
